import { useState } from 'react';
import type { LogAnalysis } from '../types';
import ImpactCard from './ImpactCard';
import SeverityBadge from './SeverityBadge';

interface CeoViewProps {
  analysis: LogAnalysis;
}

const formatINR = (amount: number): string => {
  if (amount >= 10000000) {
    return `₹${(amount / 10000000).toFixed(1)}Cr`;
  }
  if (amount >= 100000) {
    return `₹${(amount / 100000).toFixed(1)}L`;
  }
  if (amount >= 1000) {
    return `₹${(amount / 1000).toFixed(1)}K`;
  }
  return `₹${amount.toLocaleString('en-IN')}`;
};

const buildClipboardText = (a: LogAnalysis): string => {
  return [
    `INCIDENT SUMMARY`,
    `Severity: ${a.severity.toUpperCase()}`,
    ``,
    `Business Impact:`,
    `• ${a.affected_users} users affected`,
    `• ${formatINR(a.revenue_impact_inr)} estimated revenue impact`,
    `• ${a.revenue_reasoning}`,
    ``,
    `What Happened:`,
    a.business_summary,
    ``,
    `Recommended Action:`,
    a.recommended_action,
    ``,
    `— Generated by LogTalk (Powered by ScriptsHub)`,
  ].join('\n');
};

const CeoView = ({ analysis }: CeoViewProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildClipboardText(analysis));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-2xl border border-indigo-200/60 bg-gradient-to-br from-indigo-50/50 via-white to-indigo-50/30 shadow-sm dark:border-indigo-800/40 dark:from-indigo-950/30 dark:via-slate-800 dark:to-indigo-950/20">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-indigo-100/60 px-6 py-4 dark:border-indigo-800/30">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-100 dark:bg-indigo-900/50">
            <span className="text-sm font-bold text-indigo-600 dark:text-indigo-400">$</span>
          </div>
          <h3 className="text-base font-semibold text-indigo-950 dark:text-indigo-100">Business Impact</h3>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="rounded-lg border border-indigo-200/60 bg-white px-3 py-1.5 text-xs font-medium text-indigo-600 transition-all hover:bg-indigo-50 dark:border-indigo-700 dark:bg-slate-800 dark:text-indigo-400 dark:hover:bg-slate-700"
            title="Copy CEO summary to clipboard"
          >
            {copied ? 'Copied!' : 'Copy Summary'}
          </button>
          <SeverityBadge severity={analysis.severity} />
        </div>
      </div>

      {/* Hero numbers with count-up animation */}
      <div className="grid grid-cols-2 gap-4 p-6">
        <ImpactCard
          icon="👥"
          label="Users Affected"
          value={analysis.affected_users.toLocaleString('en-IN')}
          animateNumber={analysis.affected_users}
          sublabel="during incident window"
        />
        <ImpactCard
          icon="₹"
          label="Revenue Impact"
          value={formatINR(analysis.revenue_impact_inr)}
          sublabel="estimated loss"
        />
      </div>

      {/* Body */}
      <div className="space-y-5 px-6 pb-6">
        <div>
          <h4 className="mb-1.5 text-[11px] font-semibold uppercase tracking-widest text-indigo-400">
            What Happened
          </h4>
          <p className="text-sm leading-relaxed text-indigo-950 dark:text-indigo-100">{analysis.business_summary}</p>
        </div>

        <div className="rounded-xl border border-indigo-100/60 bg-indigo-50/50 p-4 dark:border-indigo-800/30 dark:bg-indigo-950/20">
          <h4 className="mb-1.5 text-[11px] font-semibold uppercase tracking-widest text-indigo-400">
            Revenue Reasoning
          </h4>
          <p className="text-sm leading-relaxed text-indigo-800 dark:text-indigo-200">{analysis.revenue_reasoning}</p>
        </div>

        <div className="rounded-xl border border-indigo-200/60 bg-gradient-to-r from-indigo-600 to-indigo-700 p-5 shadow-md shadow-indigo-200/50 dark:shadow-indigo-900/30">
          <h4 className="mb-1.5 text-[11px] font-semibold uppercase tracking-widest text-indigo-200">
            Recommended Next Step
          </h4>
          <p className="text-sm font-semibold leading-relaxed text-white">{analysis.recommended_action}</p>
        </div>
      </div>
    </div>
  );
};

export default CeoView;
